### ISSUE TITLE
Help with opening .jenc encrypted files on a computer

### ISSUE THREAD

**Issue by just-a-user-sudo** [opensource21/jpencconverter#1]
Hello! I initially asked this question [here](https://github.com/gsantner/markor/discussions/1424) but was pointed to you, opensource21.

I use the Markor Android app to create encrypted notes with the file extension ".md.jenc". I tried to use jpenconverter to decrypt files from Markor, starting by reading a [discussion](https://github.com/gsantner/markor/discussions/1372) from the Markor Github page and reading the READMEs [here](https://github.com/gsantner/markor) and [here](https://gitlab.com/opensource21/jpencconverter).

I didn't get much farther. Admittedly, I'm not familiar with Java— this is my first time trying to use Java software like this.

First, I downloaded the source code for jpencconverter and extracted it to a folder. After that, I downloaded the latest version of Java SE on my Windows 10 computer from here and installed it. The installer had already setup its own path variable, and I set a system variable to where Java is installed and named it "JAVA_HOME". And... that's all I could wrap my head around.

My question is, with Java installed and jpencconverter extracted on my computer, how exactly do I go about taking an encrypted ".md.jenc" note from Markor and then decrypting it with jpencconverter? (I tried to answer this question with the READMEs and online searches but failed to.)

**Comment by opensource21** [comment]
Hi, 
nice to see that you want to use the program. I have updated the readme. I hope it's now more clear.  If you are able to run java from the commandline it should be more clear now. There is no need to download the source.
Please look at https://gitlab.com/opensource21/jpencconverter I'm unsure how quickly the mirror will updated.

**Comment by just-a-user-sudo** [comment]
Yes, it is more clear. Downloading the source code threw me off, but now that downloaded and extracted the correct ZIP folder, I have things up and running!
