### ISSUE TITLE
Question - how to build?

### ISSUE THREAD

**Issue by clach04** [opensource21/jpencconverter#4]
My java experience is fairly limited, I've not been able to build the tool. Any hints?

    C:\code\java\jpencconverter>mvnw.cmd
    [INFO] Scanning for projects...
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  0.142 s
    [INFO] Finished at: 2024-08-11T16:13:26-07:00
    [INFO] ------------------------------------------------------------------------
    [ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

I tried a few random params like `build` with no luck :-(

My goal is to implement a non-java version of a tool to decrypt jenc/markor files. What I have so far https://github.com/clach04/jenc-py/blob/wip/jenc_reader.py  is not working, at this point I'm not sure why, so was thinking I could instrument/debug the java version.

Many thanks for adding jenc support to Markor :-)

**Comment by opensource21** [comment]
mvn package will do the job. The jar would be in the target folder.

**Comment by clach04** [comment]
Thanks @opensource21, that was the hint I needed 😀 .

This got me where I needed to be, I have been able to decrypt a V001 encrypted file from Python :-)

    mvnw.cmd package

does not create a jar due to some test failures, but it works enough for my use case. I ended up using:

    mvnw.cmd test

There are also some warnings with newer JDK:

    [WARNING] /....src/test/java/de/stanetz/jpencconverter/cryption/JavaPasswordbasedCryptionTest.java:[6,18] sun.nio.cs.US_ASCII is internal proprietary API and may be removed in a future release
    [WARNING] /....src/test/java/de/stanetz/jpencconverter/cryption/JavaPasswordbasedCryptionTest.java:[6,18] sun.nio.cs.US_ASCII is internal proprietary API and may be removed in a future release
    [WARNING] /....src/test/java/de/stanetz/jpencconverter/cryption/JavaPasswordbasedCryptionTest.java:[6,18] sun.nio.cs.US_ASCII is internal proprietary API and may be removed in a future release
